<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <Authors>dmayor, digivance</Authors>
    <Company>Digivance Technologies</Company>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;8618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Digivance.Auth.Data\Digivance.Auth.Data.csproj" />
  </ItemGroup>

</Project>
