<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Digivance Auth Service - EF Data Implementations</Title>
    <Version>0.3.0</Version>
    <Authors>dmayor, digivance</Authors>
    <Company>Digivance Technologies</Company>
    <Product>Digivance Auth Service</Product>
    <Description>EF Data layer implementations of the Digivance auth microservice api application</Description>

    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;8618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Digivance.Data" Version="0.1.0-pre.9" />
    <PackageReference Include="Digivance.Data.EntityFramework" Version="0.1.0-pre.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Digivance.Auth.Data\Digivance.Auth.Data.csproj" />
  </ItemGroup>

</Project>
