<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Title>Digivance Auth Service</Title>
    <Version>0.2.0</Version>
    <Authors>dmayor, digivance</Authors>
    <Company>Digivance Technologies</Company>
    <Product>Digivance Auth Service</Product>
    <Description>This is the Digivance auth microservice api application</Description>

    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>1701;1702;8618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(ProjectDir)wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>

  <!--
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Condition="'$(Configuration)' == 'Debug'" Command="call pnpm run build" WorkingDirectory="$(ProjectDir)../digivance_auth/app" />
  </Target>
  -->
</Project>
