name: PR Pipeline
on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get package version
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: >
        project_version=$(grep '<Version>' < ./src/Digivance.Auth.Api/Digivance.Auth.Api.csproj | sed 's/.*<Version>\(.*\)<\/Version>/\1/') &&
        echo "PROJECT_VERSION=${project_version//[$'\t\r\n']}" >> $GITHUB_ENV &&

        package_version="${project_version}-pre.${RUN_NUMBER}" &&
        echo "PACKAGE_VERSION=${package_version//[$'\t\r\n']}" >> $GITHUB_ENV

    - name: ACR Build
      uses: azure/acr-build@v1
      with:
        service_principal: ${{ secrets.ACR_PRINCIPAL }}
        service_principal_password: ${{ secrets.ACR_PASSWORD }}
        tenant: ${{ secrets.ACR_TENANT }}
        registry: ${{ secrets.ACR_REGISTRY }}
        repository: ${{ secrets.ACR_REPOSITORY }}
        tag: ${{ env.PACKAGE_VERSION }}
        dockerfile: ./docker/api/dockerfile
        branch: ${{ github.ref }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upgrade Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: ${{ secrets.ACR_REGISTRY }}
        containerAppName: auth-api-beta
        resourceGroup: ${{ secrets.AZURE_RG }}
